### ISSUE TITLE
Broken document links

### ISSUE THREAD

**Issue by xiaozhenliu-gg5** [googleapis/nodejs-redis#385]
During the client library generation, we found one broken document link in `v1/cloud_redis.proto` and `v1beta1/cloud_redis.proto`. Now we manually fix them in synthtool, but it probably need some change in proto file. Thank you!
```
[default network](/compute/docs/networks-and-firewalls#networks).
``` 
which should be 
```
[default network](https://cloud.google.com/compute/docs/networks-and-firewalls#networks).
```

**Comment by frankyn** [comment]
We can close this out. The issue has been resolved in the protos: https://github.com/googleapis/googleapis/commit/8be3770465a6cf19bea97a84b3e82b113b0239b6
