### ISSUE TITLE
Improve documentation about the APIs of redis client

### ISSUE THREAD

**Issue by mrdulin** [googleapis/nodejs-redis#386]
**Is your feature request related to a problem? Please describe.**
I have read this doc: https://googleapis.dev/nodejs/redis/latest/index.html, but this doc is about how to do the CRUD operation for memorystore instance resource on GCP. I didn't find any doc about the APIs of Redis client. For example:
```js
const instances = await client.listInstances(request);
const client = instances[0];
// ok, I am going to use the API of this Redis client
client.hmset() // I am not sure this API exists.
```
The `client.hmset` API is come from [node-redis](https://github.com/NodeRedis/node-redis) package.  So, does this package use `node-redis` as its dependency? If not, how can I know which APIs are available?  I don't want to use `console.log(client)` to check the APIs.

 **Describe the solution you'd like**
Please clarify the documentation.
 **Describe alternatives you've considered**
If there are some type definition files, it will be fine. At least I can find the API from the `.d.ts` file

**Comment by draperunner** [comment]
Yes, I also thought this was a client SDK for actually using Redis operations, but is this only for admin operations on instances?

**Comment by mrdulin** [comment]
@draperunner I don't know this library can be used as [node-redis](https://github.com/NodeRedis/node-redis) or not. It seems that it only provides the APIs encapsulate operations for the Redis server instance such as CRUD Redis server instances.
But the name of this library is too confusing

**Comment by samrocksc** [comment]
I think the title of this module is really inaccurate, the source only points to administrative tasks, not actual "client" tasks.

**Comment by rw3iss** [comment]
Wow yeah this is way off. Even the google docs suggest to use this library for client tasks.
ALSO, the documentation website itself is not lai
![Uploading 2021-02-17_21-17.png…]()
d out well! We can't even see the sidebar headers to know what each section refers to, and there's no way to expand it. See attached.
Can you break it out onto a full page??

**Comment by SeanChristopherConway** [comment]
Utterly terrible and confusing documentation. I wasted hours of my time trying to figure out how to set a hash only to discover this is not actually a Redis client for the redis memorystore. Please update.

**Comment by sofisl** [comment]
Apologies for the delay in responding, and for the confusing nature of the documentation. This library is autogenerated, so it seems that perhaps the API itself doesn't have great documentation. 

As a whole, we've made efforts to improve this documentation, including samples that show how each [method](https://github.com/googleapis/nodejs-redis/tree/main/samples/generated) should be used. You can also check out the product's documentation on [gcp](https://cloud.google.com/memorystore) for more information about it.

We are migrating this repo to google-cloud-node, and in the process closing stale issues. If this is still an issue, please feel free to reopen this bug [here](https://github.com/googleapis/google-cloud-node).
