### ISSUE TITLE
Links to documentation from README are broken (404) or redundant

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/nodejs-redis#4]
1. Node.js idiomatic client for Cloud Redis. (https://github.com/googleapis/nodejs-redis/blob/master/TBD) - probably should link to https://cloud.google.com/memorystore/docs
2. Cloud Redis Node.js Client API Reference (https://cloud.google.com/nodejs/docs/reference/redis/latest/)- link does not resolve - **this is high priority**.
3. github.com/googleapis/nodejs-redis - this link seems unnecessary 
4. Cloud Redis Documentation - same as bullet#1 and also, arguably, redundant

**Comment by crwilcox** [comment]
I have fixed 1. PR Coming. 3 & 4 are inherited from the template used by the repo-tools layout. @alexander-fenster , is there a reason we have those?

@jmdobry , can you generate the reference for this client (#2)

**Comment by danoscarmike** [comment]
@jmdobry do you have bandwidth for this this week?  We're blocked on inserting links to the libraries from cloud.google.com.  Thanks!

**Comment by danoscarmike** [comment]
This is done.  Thanks @jmdobry and @samodell for your help!
